id: I9FCD6F97
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:15:47+00:00'
last_modified: '2022-06-08T01:14:06.841132+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9730
  title: བརྒྱ་བཞིའི་ཆོ་ག་དང་བདུད་བཟློག་གི་ཆོ་ག་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9FB9:
      image_group_id: I1KG9745
      title: ''
      total_pages: 180
      order: 1
      base_file: 9FB9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
