id: I9FCD6F97
legacy_id: P004459
ocr_import_info:
  bdrc_scan_id: W1KG9730
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T14:14:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:37:09.671270+00:00'
last_modified: 2022-09-01 02:37:16.139435
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9730
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9730
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བརྒྱ་བཞིའི་ཆོ་ག་དང་བདུད་བཟློག་གི་ཆོ་ག་སོགས།
  author: རྨོར་ཆེན་ཀུན་དགའ་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.8213202297451843
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I1KG9745:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9745
      total_pages: 180
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9745.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8213202297451843
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
